# Generated by Django 3.2.6 on 2021-08-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=20, null=True)),
                ('othername', models.CharField(blank=True, max_length=20, null=True)),
                ('Surname', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.PositiveIntegerField()),
                ('skills', models.TextField(blank=True, null=True)),
                ('hobbies', models.TextField(blank=True, null=True)),
                ('Address', models.TextField(blank=True, null=True)),
                ('email', models.URLField(blank=True, null=True)),
                ('education', models.TextField(blank=True)),
                ('Experience', models.TextField(blank=True, null=True)),
                ('cv', models.FileField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
    ]
